(function(d){var a=/^\n+/,j=/^\s+(?:at)?\s+(?:([^\(]*)\()?(.*):(\d+):(\d+)\)?$/,e=/^(([^\(]*)\([^@]+){0,1}@(.*):(\d+)(\s*)/,b=20,f=function(o,p,l,q){var n=0,m,r;
if(l){l=l.replace(a,"");
}l=l.split("\n");
r=Math.min(b,l.length);
while(n<r){m=l[n++].match(q);
if(m){var k=m.length;
o.push(m.slice(k-4,k));
}}},i=function(n,l){var p=[],o=l,k;
n=n||0;
if(!l){return[];
}k=o.stack;
if(o.arguments){(k.indexOf("\n")>=0)&&f(p,n,k,j);
}else{if(k){f(p,n,k,e);
}else{if(l){if(l.sourceURL){p.push([undefined,l.sourceURL,l.line,l.expressionBeginOffset]);
}}else{var m=arguments.callee;
o=/function\s*([-$\w]+)?\s*\(/i;
while(m&&n-->0){m=m.caller;
}while(m&&p.length<b){k=m.toString().match(o);
p.push(k?[k[1]]:[]);
m=m.caller;
}}}}return p;
},h=function(l,n,m,k){d.ue_err.ec++;
d.ue.log({m:l,f:n,l:m,s:k},"jserr");
},g=function(o){if(d.ue_err.ec>d.ue_err.mxe){return;
}var n="",m=0,l=i(0,o),k;
if(l.length>0){k=l[0];
n=k[1];
m=k[2];
}h((o?o.message:0)||"Unknown error",n,m,l);
},c=function(){if(!d.ue_err.erl){return;
}var k=d.ue_err.erl.length,l;
for(l=0;
l<k;
l++){g(d.ue_err.erl[l]);
}};
c();
d.ueLogError=g;
})(ue_csm);
