/*{"version":"14231808","mac":"1:437c0764b6a70029439cdc1410806fa38e78a44038ee8870096f49d5a562e679","k":"1.1.3","created":"2012-11-14T20:17:26Z"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var g=void 0,k=!0,l=null,m=!1;function n(a){return function(){return this[a]}}var o;function p(a,c,b){var d=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){d.push.apply(d,arguments);return c.apply(a,d)}}function q(a){this.m=a;this.w=g}q.prototype.createElement=function(a,c,b){a=this.m.createElement(a);if(c)for(var d in c)c.hasOwnProperty(d)&&("style"==d?this.sa(a,c[d]):a.setAttribute(d,c[d]));b&&a.appendChild(this.m.createTextNode(b));return a};
function r(a,c,b){a=a.m.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function s(a){function c(){document.body?a():setTimeout(c,0)}c()}function t(a){a.parentNode&&a.parentNode.removeChild(a)}function u(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")}
function v(a,c){for(var b=a.className.split(/\s+/),d=[],e=0,f=b.length;e<f;e++)b[e]!=c&&d.push(b[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}function w(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return k;return m}q.prototype.sa=function(a,c){this.X()?a.setAttribute("style",c):a.style.cssText=c};q.prototype.X=function(){if(this.w===g){var a=this.m.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};
function x(a,c,b,d,e,f,h){this.Z=a;this.Qa=c;this.za=b;this.ya=d;this.La=e;this.Ka=f;this.xa=h}o=x.prototype;o.getName=n("Z");o.getVersion=n("Qa");o.getEngine=n("za");o.getEngineVersion=n("ya");o.getPlatform=n("La");o.getPlatformVersion=n("Ka");o.getDocumentMode=n("xa");function y(a,c){this.c=a;this.u=c}var ba=new x("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g);
y.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")){a=z(this);var c=B(this),b=C(this.c,/(MSIE [\d\w\.]+)/,1);if(""!=b){var d=b.split(" "),b=d[0],d=d[1];D(d);D(c);a=new x(b,d,b,d,a,c,F(this.u))}else a=new x("MSIE","Unknown","MSIE","Unknown",a,c,F(this.u))}else if(-1!=this.c.indexOf("Opera"))a:if(c=a="Unknown",b=C(this.c,/(Presto\/[\d\w\.]+)/,1),""!=b?(c=b.split("/"),a=c[0],c=c[1]):(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=C(this.c,/rv:([^\)]+)/,1),""!=b&&(c=b)),-1!=this.c.indexOf("Opera Mini/"))b=
C(this.c,/Opera Mini\/([\d\.]+)/,1),""==b&&(b="Unknown"),a=new x("OperaMini",b,a,c,z(this),B(this),F(this.u));else{if(-1!=this.c.indexOf("Version/")&&(b=C(this.c,/Version\/([\d\.]+)/,1),""!=b)){a=new x("Opera",b,a,c,z(this),B(this),F(this.u),10<=D(b));break a}b=C(this.c,/Opera[\/ ]([\d\.]+)/,1);a=""!=b?new x("Opera",b,a,c,z(this),B(this),F(this.u),10<=D(b)):new x("Opera","Unknown",a,c,z(this),B(this),F(this.u))}else if(-1!=this.c.indexOf("AppleWebKit")){a=z(this);c=B(this);b=C(this.c,/AppleWebKit\/([\d\.]+)/,
1);""==b&&(b="Unknown");d="Unknown";-1!=this.c.indexOf("Chrome")||-1!=this.c.indexOf("CrMo")||-1!=this.c.indexOf("CriOS")?d="Chrome":-1!=this.c.indexOf("Safari")?d="Safari":-1!=this.c.indexOf("AdobeAIR")&&(d="AdobeAIR");var e="Unknown";-1!=this.c.indexOf("Version/")?e=C(this.c,/Version\/([\d\.\w]+)/,1):"Chrome"==d?e=C(this.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):"AdobeAIR"==d&&(e=C(this.c,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==d?(C(e,/\d+\.(\d+)/,1),2<D(e)||D(e)):(C(b,/\d+\.(\d+)/,1),526<=D(b)||D(b));
a=new x(d,e,"AppleWebKit",b,a,c,F(this.u))}else if(-1!=this.c.indexOf("Gecko")){c=a="Unknown";d=m;-1!=this.c.indexOf("Firefox")?(a="Firefox",b=C(this.c,/Firefox\/([\d\w\.]+)/,1),""!=b&&(d=C(b,/\d+\.(\d+)/,1),c=b,d=""!=b&&3<=D(b)&&5<=parseInt(d,10))):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla");b=C(this.c,/rv:([^\)]+)/,1);if(""==b)b="Unknown";else if(!d){var d=D(b),e=parseInt(C(b,/\d+\.(\d+)/,1),10),f=parseInt(C(b,/\d+\.\d+\.(\d+)/,1),10);1<d||1==d&&9<e||1==d&&9==e&&2<=f||b.match(/1\.9\.1b[123]/)!=
l||b.match(/1\.9\.1\.[\d\.]+/)}a=new x(a,c,"Gecko",b,z(this),B(this),F(this.u))}else a=ba;return a};function z(a){var c=C(a.c,/(iPod|iPad|iPhone|Android|Windows Phone)/,1);if(""!=c)return c;a=C(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function B(a){var c=C(a.c,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);if(c||(c=C(a.c,/Windows Phone( OS)? ([^;)]+)/,2)))return c;if(c=C(a.c,/(iPhone )?OS ([\d_]+)/,2))return c;return(a=C(a.c,/Linux ([i\d]+)/,1))?a:"Unknown"}function D(a){a=C(a,/(\d+)/,1);return""!=a?parseInt(a,10):-1}function C(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}function F(a){if(a.documentMode)return a.documentMode}function ca(a,c,b){this.j=a;this.l=c;this.ca=b;this.p="wf";this.n=new G("-")}
function H(a){v(a.l,a.n.k(a.p,"loading"));w(a.l,a.n.k(a.p,"active"))||u(a.l,a.n.k(a.p,"inactive"));I(a,"inactive")}function I(a,c,b,d){if(a.ca[c])a.ca[c](b,d)}function J(a,c,b,d,e){this.j=a;this.B=c;this.D=b;this.v=d;this.I=e;this.R=0;this.ta=this.la=m}
J.prototype.watch=function(a,c,b,d,e){for(var f=a.length,h=0;h<f;h++){var i=a[h];c[i]||(c[i]=["n4"]);this.R+=c[i].length}e&&(this.la=e);for(h=0;h<f;h++)for(var i=a[h],e=c[i],j=b[i],A=0,va=e.length;A<va;A++){var $=e[A],E=this.B,K=i,aa=$;u(E.l,E.n.k(E.p,K,aa,"loading"));I(E,"fontloading",K,aa);E=p(this,this.Aa);K=p(this,this.Ba);(new d(E,K,this.j,this.D,this.v,this.I,i,$,j)).start()}};
J.prototype.Aa=function(a,c){var b=this.B;v(b.l,b.n.k(b.p,a,c,"loading"));v(b.l,b.n.k(b.p,a,c,"inactive"));u(b.l,b.n.k(b.p,a,c,"active"));I(b,"fontactive",a,c);this.ta=k;da(this)};J.prototype.Ba=function(a,c){var b=this.B;v(b.l,b.n.k(b.p,a,c,"loading"));w(b.l,b.n.k(b.p,a,c,"active"))||u(b.l,b.n.k(b.p,a,c,"inactive"));I(b,"fontinactive",a,c);da(this)};
function da(a){0==--a.R&&a.la&&(a.ta?(a=a.B,v(a.l,a.n.k(a.p,"loading")),v(a.l,a.n.k(a.p,"inactive")),u(a.l,a.n.k(a.p,"active")),I(a,"active")):H(a.B))}
function L(a,c,b,d,e,f,h,i,j){this.va=a;this.Fa=c;this.j=b;this.D=d;this.v=e;this.I=f;this.Ja=new ea;this.Da=new fa;this.T=h;this.S=i;this.Ca=j||"BESbswy";this.ma=ga(this,"arial,'URW Gothic L',sans-serif");this.na=ga(this,"Georgia,'Century Schoolbook L',serif");this.ja=this.ma;this.ka=this.na;this.$=M(this,"arial,'URW Gothic L',sans-serif");this.aa=M(this,"Georgia,'Century Schoolbook L',serif")}L.prototype.start=function(){this.Oa=this.I();this.da()};
L.prototype.da=function(){var a=this.D.W(this.$),c=this.D.W(this.aa);(this.ma!=a||this.na!=c)&&this.ja==a&&this.ka==c?(a=this.va,t(this.$),t(this.aa),a(this.T,this.S)):5E3<=this.I()-this.Oa?(a=this.Fa,t(this.$),t(this.aa),a(this.T,this.S)):(this.ja=a,this.ka=c,ha(this))};function ha(a){a.v(function(a,b){return function(){b.call(a)}}(a,a.da),25)}function ga(a,c){var b=M(a,c,k),d=a.D.W(b);t(b);return d}
function M(a,c,b){c=a.j.createElement("span",{style:ia(a,c,a.S,b)},a.Ca);r(a.j,"body",c);return c}function ia(a,c,b,d){b=a.Da.expand(b);return"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(d?"":a.Ja.quote(a.T)+",")+c+";"+b}function G(a){this.Ha=a||"-"}G.prototype.k=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Ha)};
function ea(){this.ra="'"}ea.prototype.quote=function(a){for(var c=[],a=a.split(/,\s*/),b=0;b<a.length;b++){var d=a[b].replace(/['"]/g,"");-1==d.indexOf(" ")?c.push(d):c.push(this.ra+d+this.ra)}return c.join(",")};function fa(){this.pa=ja;this.F=ka}var ja=["font-style","font-weight"],ka={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function la(a,c,b){this.Ga=a;this.Ma=c;this.F=b}la.prototype.expand=function(a,c){for(var b=0;b<this.F.length;b++)if(c==this.F[b][0]){a[this.Ga]=this.Ma+":"+this.F[b][1];break}};fa.prototype.expand=function(a){if(2!=a.length)return l;for(var c=[l,l],b=0,d=this.pa.length;b<d;b++){var e=this.pa[b];(new la(b,e,this.F[e])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":l};function N(a){this.m=a;this.w=g}N.prototype=q.prototype;N.prototype.Ea=function(){return this.m.location.hostname};
function ma(a,c,b){var d=a.m.getElementsByTagName("head")[0];if(d){var e=a.m.createElement("script");e.src=c;var f=m;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=k,b&&b(),e.onload=e.onreadystatechange=l,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e)}}N.prototype.sa=function(a,c){this.X()?a.setAttribute("style",c):a.style.cssText=c};
N.prototype.X=function(){if(this.w===g){var a=this.m.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.w=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.w};function na(a){for(var c=a.Na.join(","),b=[],d=0;d<a.ea.length;d++){var e=a.ea[d];b.push(e.name+":"+e.value+";")}return c+"{"+b.join("")+"}"}function O(a,c){this.C=a;this.H=c;this.ga={};this.fa={}}O.prototype.z=function(a){return a?(this.ga[a.L]||this.H).slice(0):this.H.slice(0)};
function oa(a,c,b){for(var d=[],e=a.C.split(",")[0].replace(/"|'/g,""),f=a.z(),h,i=[],j={},A=0;A<f.length;A++)h=f[A],0<h.length&&!j[h]&&(j[h]=k,i.push(h));b=b.qa?b.qa(e,i,d):i;c=c.L;a.ga[c]=b;a.fa[c]=d}O.prototype.watch=function(a,c,b){var d=[],e={};pa(this,c,d,e);a(d,e,b)};function pa(a,c,b,d){b.push(a.C);d[a.C]=a.z(c);a=a.fa[c.L]||[];for(c=0;c<a.length;c++){for(var e=a[c],f=e.C,h=m,i=0;i<b.length;i++)b[i]==f&&(h=k);h||(b.push(f),d[f]=e.z())}}function qa(a,c){this.C=a;this.H=c}qa.prototype.z=n("H");
function ra(a){var c=new Image(1,1);c.src=a;c.onload=function(){c.onload=l}}function P(a,c){this.L=a;this.ia=c}function sa(){this.Ra=this.A=this.J=this.K=k}function Q(a){ta.O.push(a)}function ua(a){this.j=a;this.wa=this.r=this.c=this.N=l;this.o=[];this.G=[];this.ua=this.U=this.P=this.Q=l}
function wa(a,c){a.c=c;if(a.N){var b;a:{b=a.N;for(var d=a.c,e=a.wa,f=0;f<b.O.length;f++){var h=b.O[f],i=d,j=e;j||(j=new sa);if(h.ia&&h.ia(i.getName(),i.getVersion(),i.getEngine(),i.getEngineVersion(),i.getPlatform(),i.getPlatformVersion(),i.getDocumentMode(),j)){b=h;break a}}b=l}a.r=b}}o=ua.prototype;o.supportsConfiguredBrowser=function(){return!!this.r};
o.init=function(){if(0<this.G.length){for(var a=[],c=0;c<this.G.length;c++)a.push(na(this.G[c]));var c=this.j,a=a.join(""),b=this.j.m.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));r(c,"head",b)}};
o.load=function(a,c){var b=this.r.L;if(this.U)for(var d=xa(this.U,b),e=0;e<this.o.length;e++)oa(this.o[e],this.r,d);this.Q&&(d=[],this.P&&(d=new ya(this.j,this.r,this.o),d=za(this.P,b,d)),b=this.Q.k("https:"==this.j.m.location.protocol,Aa(b,d)),r(this.j,"head",this.j.createElement("link",{rel:"stylesheet",href:b})));a&&s(function(a,b,c,e){return function(){for(var d=0;d<a.o.length;d++)a.o[d].watch(b,c,e&&d==a.o.length-1)}}(this,a,this.r,c))};
o.collectFontFamilies=function(a,c){for(var b=0;b<this.o.length;b++)pa(this.o[b],this.r,a,c)};o.performOptionalActions=function(a){this.Y&&s(function(a,b,d,e){return function(){var b=a.Y;if(b.oa){var h=window.__adobewebfontsappname__,h=h?h.toString().substr(0,20):"";ra(b.oa.k("https:"==e.m.location.protocol,{host:encodeURIComponent(e.m.location.hostname),app:encodeURIComponent(h),_:(+new Date).toString()}))}b=a.Y;b.ba&&(b=b.ba.k(d,e),r(e,"body",b))}}(this,a,this.c,this.j))};
function R(a,c,b,d){this.Ia=a;this.j=c;this.l=b;this.v=d;this.q=[]}R.prototype.M=function(a){this.q.push(a)};R.prototype.load=function(a,c){var b=a,d=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)d=b||{},b=[];if(b.length)for(var e=this,f=b.length,h=0;h<b.length;h++)Ba(this,b[h],function(){0==--f&&Ca(e,d)});else Ca(this,d)};function Ba(a,c,b){ma(a.j,a.Ia.k("https:"==a.j.m.location.protocol,{id:encodeURIComponent(c)}),b)}
function Ca(a,c){if(0!=a.q.length){for(var b=new ca(a.j,a.l,c),d=m,e=0;e<a.q.length;e++)a.q[e].init(),d=d||a.q[e].supportsConfiguredBrowser();d?(u(b.l,b.n.k(b.p,"loading")),I(b,"loading"),Da(a,b)):H(b);a.q=[]}}function Da(a,c){function b(a,b,c){d.watch(a,b,{},L,c)}for(var d=new J(a.j,c,{W:function(a){return a.offsetWidth}},a.v,function(){return+new Date}),e=0;e<a.q.length;e++){var f=a.q[e];f.supportsConfiguredBrowser()&&(f.load(b,e==a.q.length-1),f.performOptionalActions(window))}}
function S(a,c){this.ha=a;this.v=c;this.q=[]}S.prototype.M=function(a){this.q.push(a)};S.prototype.load=function(){var a=this.ha.__webfonttypekitmodule__;if(a)for(var c=0;c<this.q.length;c++){var b=this.q[c],d=a[b.ua];if(d){var e=this.v;d(function(a,c,d){var c=[],j={};wa(b,a);b.supportsConfiguredBrowser()&&(b.init(),b.load(l,e),b.collectFontFamilies(c,j),b.performOptionalActions(window));d(b.supportsConfiguredBrowser(),c,j)})}}};function T(a,c){this.Z=a;this.qa=c}T.prototype.getName=n("Z");
function Ea(a){var c=U;Fa(c,a.getName())||c.V.push(a)}function Fa(a,c){for(var b=0;b<a.V.length;b++){var d=a.V[b];if(c===d.getName())return d}return l}function xa(a,c){var b=a.s[c];return b?Fa(a,b):l}function za(a,c,b){for(var d=[],a=a.t[c]||[],c=0;c<a.length;c++){var e;a:switch(a[c]){case "observeddomain":e=new Ga(b.j);break a;case "fontmask":e=new Ha(b.r,b.o);break a;default:e=l}e&&d.push(e)}return d}function ya(a,c,b){this.j=a;this.r=c;this.o=b}function Ga(a){this.j=a}
Ga.prototype.toString=function(){return encodeURIComponent(this.j.Ea?this.j.m.location.hostname:document.location.hostname)};function Ha(a,c){this.r=a;this.o=c}Ha.prototype.toString=function(){for(var a=[],c=0;c<this.o.length;c++)for(var b=this.o[c],d=b.z(),b=b.z(this.r),e=0;e<d.length;e++){var f;a:{for(f=0;f<b.length;f++)if(d[e]===b[f]){f=k;break a}f=m}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(d=a.length;0<d;d-=4)b=a.slice(0>d-4?0:d-4,d),c.unshift(parseInt(b,2).toString(16));return c.join("")};
function V(a){this.Pa=a}V.prototype.k=function(a,c){var b=c||{},d=this.Pa.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,d){return d&&b[c]?"/"+b[c].join("/"):b[c]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function Aa(a,c){for(var b=[],d=0;d<c.length;d++)b.push(c[d].toString());return{format:a,extras:b}}var ta=new function(){this.O=[]};
Q(new P("a",function(a,c,b,d,e,f){if(m||("Windows"==e&&"Unknown"==f?k:m)||("Ubuntu"==e||"Linux"==e?k:m))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
Q(new P("b",function(a,c,b,d,e,f,h,i){var j;j=m||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b){if("AdobeAIR"==a){var c=/([0-9]+.[0-9]+)/.exec(b);if(c)return 2.5<=parseFloat(c[1])}return m}(a,c,b,d,e,f,h,i)}));
Q(new P("a",function(a,c,b,d,e,f,h,i){var j;j=(j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,d,e,f,h,i))||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i);return!j&&!("Ubuntu"==
e||"Linux"==e?k:m)?m:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c){var d=parseFloat(c[1]),e=parseInt(c[2],10),c=parseInt(c[3],10);if(!(6<=d)&&(4<d||4==d&&249<e||4==d&&249==e&&4<=c))return k}}return m}(a,c,b,d,e,f,h,i)}));
Q(new P("d",function(a,c,b,d,e,f,h,i){var j;j=(j=(j=(j=(j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,d,e,f,h,i))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i))||("Ubuntu"==
e||"Linux"==e?k:m)||function(a,b,c,e,d,f,h,i){a=/([0-9]+).([0-9]+)/.exec(f);return i.A&&"Android"==d&&a?(d=parseInt(a[1],10),i=parseInt(a[2],10),3==d&&1<=i||3<d):m}(a,c,b,d,e,f,h,i))||"CrOS"==e||function(a,b,c,e,d,f,h,i){return i.J&&"iPad"==d?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,d,e,f,h,i))||function(a,b,c,d,e,f,h,i){return i.K&&("iPhone"==e||"iPod"==e)?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b){if("Chrome"==a){var c=
/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return k}}(a,c,b,d,e,f,h,i)}));
Q(new P("a",function(a,c,b,d,e,f,h,i){var j;j=(j=m||function(a,b,c,e,d,f,h,i){return i.J&&"iPad"==d&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):m}(a,c,b,d,e,f,h,i))||function(a,b,c,e,d,f,h,i){if(i.K&&("iPhone"==d||"iPod"==d))if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b;return m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b){if("Chrome"==a){var c=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(b);if(c&&6<=parseFloat(c[1]))return k}}(a,
c,b,d,e,f,h,i)}));Q(new P("a",function(a,c,b,d,e,f,h,i){var j;j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,d,e,f,h,i);return!j&&!("Ubuntu"==e||"Linux"==e?k:m)?m:function(a,b,c,e){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(e)&&!a.test(e)):m}(a,c,b,d,e,f,h,i)}));
Q(new P("b",function(a,c,b,d,e,f,h,i){var j;j=m||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b,c,e){return"Gecko"==c?(a=/1.9.1b[1-3]{1}/,/1.9.1/.test(e)&&!a.test(e)):m}(a,c,b,d,e,f,h,i)}));
Q(new P("d",function(a,c,b,d,e,f,h,i){var j;j=(j=(j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):m}(a,c,b,d,e,f,h,i))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i))||("Ubuntu"==
e||"Linux"==e?k:m)||i.A&&"Android"==e;return!j?m:function(a,b,c,e){return"Gecko"==c&&(b=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(e))?(a=parseFloat(b[1]),b=parseInt(b[3],10),1.9<a||1.9<=a&&1<b):m}(a,c,b,d,e,f,h,i)}));
Q(new P("i",function(a,c,b,d,e,f,h,i){var j;j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b,c,e,d,f,i){if("MSIE"==a)return(a=/([0-9]+.[0-9]+)/.exec(b))?6<=parseFloat(a[1])&&(i===g||9>i):m}(a,c,b,d,e,f,h,i)}));
Q(new P("d",function(a,c,b,d,e,f,h){if(!(c=m))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==e&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=m;a=c||("Windows"==e&&"6.0"==f?k:m)?"MSIE"==a?9<=h:g:m;return a}));Q(new P("d",function(a,c,b,d,e,f,h,i){if(!(c=m))f=/^([0-9]+)/.exec(f),c=i.Ra&&"Windows Phone"==e&&f?8<=parseInt(f[1],10):m;return!c?m:"MSIE"==a}));
Q(new P("a",function(a,c,b,d,e,f,h,i){var j;j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):m}(a,c,b,d,e,f,h,i);return!j&&!("Ubuntu"==e||"Linux"==e?k:m)?m:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return m}(a,c,b,d,e,f,h,i)}));
Q(new P("b",function(a,c,b,d,e,f,h,i){var j;j=m||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b){if("Opera"==a){var c=parseFloat(b);return 10.54<=c&&11.1>c}return m}(a,c,b,d,e,f,h,i)}));
Q(new P("d",function(a,c,b,d,e,f,h,i){var j;j=(j=(j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):m}(a,c,b,d,e,f,h,i))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i))||("Ubuntu"==
e||"Linux"==e?k:m)||i.A&&"Android"==e;return!j?m:"Opera"==a?11.1<=parseFloat(c):m}));Q(new P("b",function(a,c,b,d,e,f,h,i){var j;j=m||function(a,b,c,e,d,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),10<d||10==d&&4<=f):"Macintosh"==d&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b,c,d){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(d))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):m}(a,c,b,d,e,f,h,i)}));
Q(new P("a",function(a,c,b,d,e,f,h,i){var j;j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,d,e,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==e&&a?(e=parseInt(a[1],10),a=parseInt(a[2],10),6<e||6==e&&1<=a):m}(a,c,b,d,e,f,h,i);return!j?m:function(a,b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?(a=parseFloat(a[1]),525.13<=a&&534.5>a):m}(a,c,b,d,e,f,h,i)}));
Q(new P("d",function(a,c,b,d,e,f,h,i){var j;j=(j=m||("Windows"==e&&"5.1"==f?k:m)||("Windows"==e&&"5.2"==f?k:m)||("Windows"==e&&"6.0"==f?k:m)||function(a,b,c,e,d,f){a=/^([0-9]+).([0-9]+)/.exec(f);return"Windows"==d&&a?(d=parseInt(a[1],10),a=parseInt(a[2],10),6<d||6==d&&1<=a):m}(a,c,b,d,e,f,h,i))||function(a,b,c,d,e,f){a=/^([0-9]+)(_|.)([0-9]+)/.exec(f);return"Macintosh"==e&&a?(e=parseInt(a[1],10),f=parseInt(a[3],10),10<e||10==e&&4<=f):"Macintosh"==e&&"Unknown"==f?k:m}(a,c,b,d,e,f,h,i);return!j?m:function(a,
b,c,e){return"Safari"==a&&"AppleWebKit"==c&&(a=/([0-9]+.[0-9]+)/.exec(e))?534.5<=parseFloat(a[1]):m}(a,c,b,d,e,f,h,i)}));
Q(new P("a",function(a,c,b,d,e,f,h,i){var j;j=(j=(j=m||function(a,b,c,e,d,f,i,h){a=/([0-9]+).([0-9]+)/.exec(f);return h.A&&"Android"==d&&a?(d=parseInt(a[1],10),h=parseInt(a[2],10),2==d&&2<=h||3==d&&1>h):m}(a,c,b,d,e,f,h,i))||function(a,b,c,e,d,f,h,i){return i.J&&"iPad"==d&&(a=/^([0-9]+)_([0-9]+)/.exec(f))?(b=parseInt(a[2],10),4==parseInt(a[1],10)&&2<=b):m}(a,c,b,d,e,f,h,i))||function(a,b,c,e,d,f,i,h){if(h.K&&("iPhone"==d||"iPod"==d))if(a=/^([0-9]+)_([0-9]+)/.exec(f))return b=parseInt(a[2],10),4==
parseInt(a[1],10)&&2<=b;return m}(a,c,b,d,e,f,h,i);return!j?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?k:m}));Q(new P("f",function(a,c,b,d,e,f,h,i){if(!(c=m))f=/([0-9]+).([0-9]+)/.exec(f),i.A&&"Android"==e&&f?(i=parseInt(f[1],10),f=parseInt(f[2],10),c=3==i&&1<=f||3<i):c=m;return!c?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?k:m}));
Q(new P("d",function(a,c,b,d,e,f,h,i){var j;j=(j=m||function(a,b,c,d,e,f,h,i){return i.J&&"iPad"==e?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,d,e,f,h,i))||function(a,b,c,e,d,f,i,h){return h.K&&("iPhone"==d||"iPod"==d)?(a=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(a[1],10):m:m}(a,c,b,d,e,f,h,i);return!j?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==e||"iPad"==e)?k:m}));var U=new function(){this.V=[];this.s={}};Ea(new T("AllFonts",function(a,c){return c}));
Ea(new T("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var d=0;d<c.length;d++){var e=c[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;b.push(new qa(f,[e]))}a={};for(e=0;e<c.length;e++)b=c[e],d=b.charAt(1),(a[d]||(a[d]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<b.length;e++)for(var f=b[e],h=0;h<f.length;h++){var i=f[h];if(a[i]){d=d.concat(a[i]);break}}b=d;d={};a=[];for(e=0;e<b.length;e++)f=b[e],d[f]||(d[f]=k,a.push(f));b=[];for(d=0;d<c.length;d++){e=c[d];
for(f=0;f<a.length;f++)h=a[f],h==e&&b.push(h)}return b}));U.s.a="AllFonts";U.s.b="AllFonts";U.s.d="AllFonts";U.s.e="AllFonts";U.s.f="AllFonts";U.s.g="AllFonts";U.s.h="AllFonts";U.s.i="DefaultFourFontsWithSingleFvdFamilies";var W=new function(){this.t={}};W.t.a=[];W.t.b=[];W.t.d=[];W.t.e=[];W.t.f=["observeddomain"];W.t.g=["observeddomain"];W.t.h=["observeddomain"];W.t.i=["observeddomain","fontmask"];window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Ia=function(a,c){setTimeout(a,c)},X=new R(new V("//fonts.wsj.com/{id}.js"),new N(document),document.documentElement,Ia),Y=new S(window,Ia);window.Typekit.load=function(){X.load.apply(X,arguments)};window.Typekit.addKit=function(){X.M.apply(X,arguments)}}var Ja=l,Ka,Z,Ja=new V("//p.typekit.net/p.gif?a=74&f=1779.1780.1781.1782.1783.1784.1785.1786.1787.1788&h={host}&ht=sh&k=rtn5rej&s=1&_={_}");Ka=new function(){var a=Ja;this.ba=l;this.oa=a};Z=new ua(new N(document));
Z.ua="rtn5rej";Z.Q=new V("//fonts.wsj.com/k/rtn5rej-{format}.css?3bb2a6e53c9684ffdc9a9bf61d5b2a62d6138ae381e419350a9e4b6a2ea4b26f81a44a9a3fd76d172c69fe2029381463ad3b2b9f57efd95582df0742cea8deb803244f67617f9d0625a9b0c6afe6273d11b54d031342ae7abf5f75e41d0992b0561404dbb25e8e9e7467fa");Z.Y=Ka;Z.o.push(new O("kulturista-web","n1,i1,n3,i3,n4,i4,n6,i6,n7,i7".split(",")));Z.G.push(new function(){this.Na=[".tk-kulturista-web"];this.ea=[{name:"font-family",value:'"kulturista-web",serif'}]});Z.N=ta;Z.P=W;
Z.U=U;Y&&Y.ha.__webfonttypekitmodule__?(Y.M(Z),Y.load()):(wa(Z,(new y(navigator.userAgent,document)).parse()),window.Typekit.addKit(Z));
})(this,document);