

/* mediaMatrix Starts */

(function($){window.TwisterMediaMatrix=new function(){var self=this;this.MAX_PAGINATE=15;this.MAX_PAGINATE_FLEX=5;this.MAX_SHOW_ALL=20;this.SHOW_ALL_ENABLED=true;this.AJAX_HANDLER="/gp/media-matrix/fetch-expansion-data.html";this.AJAX_HANDLER_POPOVER="/gp/media-matrix/fetch-popover-data.html";var BUCKET_CLOSED=0;var BUCKET_SEMI_CLOSED=1;var BUCKET_OPEN=2;var BUCKET_DISABLED=3;this.buckets={};this.requestType;this.selectedASIN;this.selectedBucket;this.parentASIN;this.totalCount=0;this.hiddenCount=0;this.bucketCount=0;this.productGroupID;this.loggingEnabled;this.logData={};this.loadingString;this.errorString;this.loadingImage;this.sr;this.qid;var logCount=0;var expandCount=0;var collapseCount=0;var popoverCount=0;if(typeof(touchDeviceDetected)!="undefined"){this.touchDeviceDetected=touchDeviceDetected}else{touchDeviceDetected=false}
this.clickOrTouchEnd="click";if(touchDeviceDetected){this.clickOrTouchEnd="touchend";}
this.initialize=function(b,hiddenCount,rt,selected,parent,pid,loading,error,img,loggingEnabled,sr,qid){this.loggingEnabled=loggingEnabled;if(this.loggingEnabled){this.log("initStart");this.log("jsStart",window._tmm_1);this.log("jsEnd",window._tmm_2);this.log("renderEnd",window._tmm_3);$(window).unload(function(){self.sendLogs();});}
this.hiddenCount=parseInt(hiddenCount);this.requestType=rt;this.selectedASIN=selected;this.parentASIN=parent;this.productGroupID=pid;this.loadingString=loading;this.errorString=error;this.sr=sr;this.qid=qid;this.loadingImage='<img width="11" height="11" src="'+img+'"/>';for(var bucket in b){var state={};state.winner=$("#"+bucket+"_winner");state.body=$("#"+bucket+"_body");state.showMoreLink=$("#"+bucket+"_showMoreLink");state.showFewerLink=$("#"+bucket+"_showFewerLink");state.showMoreButton=$("#"+bucket+"_showMoreButton");state.showFewerButton=$("#"+bucket+"_showFewerButton");state.hasExpanded=false;state.requestPending=false;state.hasReachedSelectedASIN=false;state.n=parseInt(b[bucket].n);state.p=parseInt(b[bucket].start);state.expansion=state.n>1?BUCKET_CLOSED:BUCKET_DISABLED;var ar=state.body.find("tr.activeRow");if(ar.length>0){this.selectedBucket=bucket;if(state.n>2){state.expansion=BUCKET_SEMI_CLOSED;}else{state.expansion=BUCKET_DISABLED;}}
this.bucketCount++;this.totalCount+=state.n;this.buckets[bucket]=state;}
this.initializeDisplay();this.log("initEnd");};this.initializeDisplay=function(){var clickOrTouchEnd=this.clickOrTouchEnd;if(this.SHOW_ALL_ENABLED&&this.totalCount<=this.MAX_SHOW_ALL&&this.hiddenCount>0){$("#tmm_showMoreFormats a, #tmm_showMoreFormat a").bind(clickOrTouchEnd,function(){for(bucket in self.buckets){(self.expandBucket(bucket))();}
return false;});$("#tmm_showFewerFormats a").bind(clickOrTouchEnd,function(){for(bucket in self.buckets){(self.collapseBucket(bucket,false))();}
return false;});this.updateShowMoreFormatsLink();}
for(bucket in this.buckets){var state=this.buckets[bucket];if(state.expansion!=BUCKET_DISABLED){state.showMoreButton.bind(clickOrTouchEnd,this.expandBucket(bucket)).css("visibility","");state.showFewerButton.bind(clickOrTouchEnd,this.collapseBucket(bucket,false));state.showMoreLink.find("a").bind(clickOrTouchEnd,this.expandBucket(bucket));state.showFewerLink.find("a").bind(clickOrTouchEnd,this.collapseBucket(bucket,true));}
state.winner.add(state.body).find("tr").each(function(){self.initializeRow(this);});}};this.initializeRow=function(row){row=$(row);if(row.hasClass("notPopoverRow"))
return;if(row.hasClass("activeRow")&&disableWinnerPopup){return;}
var touchDeviceDetected=this.touchDeviceDetected;var clickOrTouchEnd=this.clickOrTouchEnd;row.find("a").each(function(){$(this).bind(clickOrTouchEnd,function(e){e.stopPropagation();});});if(!touchDeviceDetected){row.bind("mouseenter",function(){$("table.twisterMediaMatrix .popoverRow").removeClass("popoverRow");if(!row.hasClass("activeRow"))
row.addClass("selectRow");}).bind("mouseleave",function(){row.removeClass("selectRow");});}
this.initPopover(row);};this.initPopover=function(row){var ajaxHandlerPopover=this.AJAX_HANDLER_POPOVER;var productCategory=this.requestType;var sr=this.sr;var qid=this.qid;var pid=this.productGroupID;var hover=!this.touchDeviceDetected;var clickOrTouchEnd=this.clickOrTouchEnd;if(typeof amznJQ!="undefined"){amznJQ.available("popover",function(){var popContent=row.find(".tmm_popover");if(!row.hasClass("activeRow")){row.bind(clickOrTouchEnd,function(e){var url=row.find("td.tmm_bookTitle a:first").attr("href");window.location.href=url;});}
var popoverOptions={showOnHover:hover,showCloseButton:false,location:["left","right"],locationAlign:"middle",locationMargin:20,width:260,hoverShowDelay:450,hoverHideDelay:300,followLink:true,focusOnShow:false,attached:true,group:"tmm_popover",onFilled:function(p){var img=p.find("div.image img");if(!img.attr("src")){img.css("visibility","hidden");var url=img.attr("hsrc");if(url){var preload=new Image();preload.src=url;if(preload.complete){img.attr("src",url);img.css("visibility","");}else{preload.onload=function(){img.attr("src",url);img.css("visibility","");};}}}
if(!row.hasClass("activeRow")){row.addClass("popoverRow");}},onShow:function(p){var pid="showPop_"+logCount++;p.attr("pid",pid);popoverCount++;self.log(pid,"s:"+getTime());self.log(pid,"e:"+getTime());},onHide:function(p){var pid=p.attr("pid");self.log(pid,"cl:"+getTime());p.removeAttr("pid");row.removeClass("popoverRow");}};if(popContent.length==0){var asin=row.attr('id').split("_")[1];var metaBinding;var curEle=document.getElementById(row.attr('id'));if(curEle){var parent=curEle.parentNode;if(parent){var parentId=parent.id;if(parentId){var index=parentId.indexOf('_meta_binding');if(index>0){metaBinding=parentId.substring(0,index+13);}}}}
popoverOptions.destination=ajaxHandlerPopover+"?productCategory="+productCategory+"&asin="+asin+"&sr="+sr+"&qid="+qid+"&metaBinding="+metaBinding+"&productGroupID="+pid;popoverOptions.cacheable=true;}else{popoverOptions.localContent=popContent;}
row.amazonPopoverTrigger(popoverOptions);});}};this.expandBucket=function(bucket){var state=self.buckets[bucket];var clickOrTouchEnd=this.clickOrTouchEnd;expandCount++;return function(){if(state.expansion!=BUCKET_DISABLED){self.clearErrors();if(state.expansion==BUCKET_OPEN||!state.hasExpanded){if(!state.requestPending){var count=self.getNumToFetch(state.n-state.p);if(count>0){var rid="bucketExpand_"+logCount++;self.log(rid,"b:"+bucket);if(state.expansion==BUCKET_OPEN){state.loader=$(self.loadingImage).css("margin-left","7px");state.showMoreLink.find("a").after(state.loader);}else{state.showMoreButton.hide();if(state.showMoreButton.parent().hasClass("tmm_buttonTD")){state.loader=$(self.loadingImage).css("margin-left","5px");}else{state.loader=$(self.loadingImage).css("padding","2px 0");}
state.showMoreButton.before(state.loader);}
self.log(rid,"l:"+getTime());state.loader.bind(clickOrTouchEnd,function(e){e.stopPropagation();});state.requestPending=true;self.getRows(bucket,state.p,count,rid);}}}else{state.showMoreButton.hide();state.showFewerButton.show();var rows=state.body.find("tr:not('.activeRow')");rows.show();self.hiddenCount-=rows.length;self.updateShowMoreLink(bucket);self.updateShowMoreFormatsLink();}
state.expansion=BUCKET_OPEN;}
return false;};};this.completeAjax=function(bucket,count,rid){var state=this.buckets[bucket];return function(d){var content=$(d).filter("tr");if(content.length>0){state.p+=count;state.hasExpanded=true;state.requestPending=false;var timer=0;var selectedRow=state.body.find("tr.activeRow");content.each(function(i){var row=$(this);if(selectedRow.length>0&&(row.attr("id")=="tmm_"+self.selectedASIN)){state.hasReachedSelectedASIN=true;}else{if(state.expansion==BUCKET_OPEN){self.hiddenCount--;}else{row.hide();}
if(state.hasReachedSelectedASIN||selectedRow.length==0){state.body.append(row);}else{selectedRow.before(row);}
self.initializeRow(row);}});if(state.expansion==BUCKET_OPEN){self.updateShowMoreLink(bucket);self.updateShowMoreFormatsLink();state.showMoreButton.hide();state.showFewerButton.show();self.log(rid,"e:"+getTime());}
state.loader.remove();state.loader=null;}else{state.requestPending=false;self.onError(bucket);}};};this.collapseBucket=function(bucket,adjustViewPort){var state=self.buckets[bucket];collapseCount++;return function(){if(state.expansion!=BUCKET_DISABLED){self.clearErrors();state.showMoreButton.show();state.showFewerButton.hide();state.showMoreLink.hide();state.showFewerLink.hide();var rows=state.body.find("tr:not('.activeRow'):visible");rows.hide();self.hiddenCount+=rows.length;if(bucket==self.selectedBucket){state.expansion=BUCKET_SEMI_CLOSED;}else{state.expansion=BUCKET_CLOSED;}
self.updateShowMoreFormatsLink();if(adjustViewPort){$pos=$("#"+bucket+"_winner").position();window.scrollTo($pos.left,$pos.top);}}
return false;};};this.updateShowMoreLink=function(bucket){var state=this.buckets[bucket];var numRemaining=state.n-state.p;if(numRemaining>0){$("#"+bucket+"_showMoreVariationsCount").text(this.getNumToFetch(numRemaining));showRow(state.showMoreLink);}else{state.showMoreLink.hide();if(state.n>(this.MAX_PAGINATE+this.MAX_PAGINATE_FLEX+1))
showRow(state.showFewerLink);}};this.updateShowMoreFormatsLink=function(){if(this.SHOW_ALL_ENABLED&&this.totalCount<=this.MAX_SHOW_ALL){if(this.hiddenCount>0){if(this.hiddenCount>1){$("#tmm_showMoreFormat").hide();showRow($("#tmm_showMoreFormats"));$("#tmm_hiddenVariationsCountFormats").text(this.hiddenCount);}else{$("#tmm_showMoreFormats").hide();showRow($("#tmm_showMoreFormat"));$("#tmm_hiddenVariationsCountFormat").text(this.hiddenCount);}
$("#tmm_showFewerFormats").hide();}else{$("#tmm_showMoreFormats, #tmm_showMoreFormat").hide();showRow($("#tmm_showFewerFormats"))}}};this.getNumToFetch=function(numRemaining){if(numRemaining<=(this.MAX_PAGINATE+this.MAX_PAGINATE_FLEX)){return numRemaining;}else{return this.MAX_PAGINATE;}};this.getRows=function(bucket,start,count,rid){var requestData={metaBinding:bucket,productCategory:this.requestType,parentAsin:this.parentASIN,startIndex:start,count:count,sr:this.sr,qid:this.qid,productGroupID:this.productGroupID};this.log(rid,"p:"+start);this.log(rid,"n:"+count);this.log(rid,"s:"+getTime());$.ajax({type:"GET",cache:false,url:this.AJAX_HANDLER,data:requestData,timeout:8000,success:this.completeAjax(bucket,count,rid),error:function(){self.buckets[bucket].requestPending=false;self.onError(bucket);}});};this.onError=function(bucket){if(this.logData.errors){this.logData.errors++;}else{this.logData.errors=1;}
var state=this.buckets[bucket];state.loader.remove();state.loader=null;if(state.hasExpanded&&state.expansion==BUCKET_OPEN){state.showMoreLink.find("td:eq(1)").append('<span class="tmm_error" style="padding-left: 7px;">'+this.errorString+'</span>');}else{(this.collapseBucket(bucket,false))();state.body.prepend('<tr class="tmm_error"><td colspan="5">'+this.errorString+'</td></tr>');}};this.clearErrors=function(){$("table.twisterMediaMatrix .tmm_error").remove();};this.log=function(key,val){if(this.loggingEnabled){if(this.logData[key]){this.logData[key].push(val||+new Date());}else{this.logData[key]=[val||+new Date()];}}};this.sendLogs=function(){if(typeof window.clientLogger!='undefined'){this.logData["productGroupID"]=this.productGroupID;var browser;if($.browser.msie){browser="msie";}else if($.browser.mozilla){browser="mozilla";}else if($.browser.safari){browser="safari";}
this.logData["browser"]=browser;this.logData["browserVersion"]=$.browser.version;this.logData["popoverCount"]=popoverCount;this.logData["expandCount"]=expandCount;this.logData["collapseCount"]=collapseCount;clientLogger.sendCLOGEntry("twister","media_popover",this.logData);}};var getTime=function(){if(self.logData['jsStart'])
return(+new Date())-self.logData['jsStart'][0];else
return 0;};var showRow=function(elem){if($.browser.mozilla){elem.css("display","table-row");}else{elem.show();}};};})(jQuery);if(typeof amznJQ!="undefined"){amznJQ.declareAvailable("twister-media-matrix");}

/* mediaMatrix Ends */

